mongo:
  image: mongo:jessie
  volumes:
    - ./.dbdata:/data/db

redis:
  image: redis:3.2-alpine
  volumes:
    - ./.redis:/etc/redis/database

si32-api:
  build: .
  ports:
    - "3000:3000"
  volumes:
    - ./:/app
    - node_modules:/app/node_modules
  environment:
    PORT: 3000
  command: >
      /bin/sh -c "
        sleep 2;
        nodemon app/index.js
      "
  links:
    - mongo
    - redis
